services:
  fewo-website:
    image: ghcr.io/larswillrich/fewo-willrich:latest
    container_name: fewo-website
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.fewo.rule=Host(`fewo-willrich.de`)
      - traefik.http.routers.fewo.tls=true
      - traefik.http.routers.fewo.entrypoints=web,websecure
      - traefik.http.routers.fewo.tls.certresolver=mytlschallenge
      - traefik.http.services.fewo.loadbalancer.server.port=80
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
