server {
    listen 80;
    server_name _;

    location /fewo/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /fewo/index.html;
    }

    location /fewo {
        return 301 /fewo/;
    }
}
